// <auto-generated />
using IndtApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndtApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IndtApi.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelDeAcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "aaaaaa@gmail.com",
                            NivelDeAcesso = "Administrador",
                            Nome = "aaaaaa",
                            Senha = "12312",
                            Sobrenome = "bbbbbbbbb"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bbbbbb@gmail.com",
                            NivelDeAcesso = "Comum",
                            Nome = "bbbbbb",
                            Senha = "45678",
                            Sobrenome = "ccccccccc"
                        },
                        new
                        {
                            Id = 3,
                            Email = "cccccc@gmail.com",
                            NivelDeAcesso = "Comum",
                            Nome = "cccccc",
                            Senha = "23123",
                            Sobrenome = "ddddddddd"
                        },
                        new
                        {
                            Id = 4,
                            Email = "dddddd@gmail.com",
                            NivelDeAcesso = "Comum",
                            Nome = "dddddd",
                            Senha = "21312",
                            Sobrenome = "eeeeeeeee"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
